[build-system]
requires = ["setuptools>=42", "wheel", "setuptools-git-versioning>=2.0,<3"]
build-backend = "setuptools.build_meta"

[project]
name = "facebase-ml-tools"
version = "0.0.1"
authors = [
    {name = "Your Name", email = "you@yourdomain.com"},
]
description = "Utilities to simplify use of Dervia and Pandas"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools-git-versioning]
enabled = true
version_file = "VERSION"
count_commits_from_version_file = true

[metadata]
license = "Apache 2.0"
keywords = ["facebase"]